# Configuration for Lichess Events Discord Bot

logging:
  # Global logging level: DEBUG, INFO, WARNING, ERROR, CRITICAL
  level: INFO
  # When set to true, enables DEBUG-level logging globally
  verbose: false
  # File handler settings
  file:
    # Pattern for daily error log filename (strftime directive)
    filename_pattern: "error_log_%Y_%m_%d.log"
    # Log level for file handler
    level: WARNING
  # Console handler settings
  console:
    # Log level for console output
    level: WARNING
  # Discord logging channel settings
  discord:
    # Log level for messages sent to Discord channels
    level: ERROR
    # Whether to post event notifications (create/update/delete)
    events: true

scheduler:
   # Enable or disable automatic background sync per server
   auto_sync: true
   # Cron expression for scheduled sync (crontab format)
   cron: "0 3 * * *"

performance:
   # Cache settings for Lichess API responses
   cache:
     # How long to cache tournament data (in minutes)
     ttl_minutes: 15
   # Rate limiting and batching
   batch_size: 5
   # Delay between batches to avoid rate limits (in seconds)
   batch_delay: 1
